version: "3.9"
services:
  app:
    container_name: BadBank2
    restart: always
    build: .
    ports: 
      - '80:3000'
    links: 
      - mongo
  mongo:
    container_name: badbankdb
    image: mongo
    ports:
      - '27017:27017'